### ISSUE TITLE
first time user of chromium-bin, unsure how to handle sandbox issue

### ISSUE THREAD

**Issue by thunderrd** [stha09/gpo-stha09#1]
Hi, I've just discovered your overlay and am trying chromium-bin for the first time.

Upon emerging the package I get the following error when attempting to start chromium-bin:

```
thunderrd@Q6600:~$ chromium-bin
[24897:24897:0123/012628.801211:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
Trace/breakpoint trap
```

I've looked at the document in the webpage provided in the output but can't figure out exactly what to do to create the needed sandbox environment.  Am using --no-sandbox at present, can you advise as to the procedure [for a novice with chromium]?

Thanks for any info you can provide.

**Comment by stha09** [comment]
The ebuild checks some kernel features that are required to make the namespace sandbox work, especially USER_NS. Please double check, that all no warnings are reported in this step. You can also try to merge with USE=suid. This installs the suid sandbox, which is a fallback option for the namespace sandbox.

**Comment by thunderrd** [comment]
Thanks for the help, re-emerging with +suid did the trick.
USER_NS is already set in the kernel.

Have a great day!

**Comment by joewis** [comment]
Hi,
I also have discovered your chromium-bin overlay a while back, first of all thanks for this - it's keeping my ancient 32bit netbook alive.

For chromium 88 it seems the i686 packages at ~sultan are 64bit binaries, maybe have a look what happened before building 89. Cheers :)

**Comment by stha09** [comment]
@joewis Moved the build to another server and had wrong location for x86 in the packaging script. Thanks for noticing.
